# Generated by Django 4.1.7 on 2023-02-25 17:00

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', verbose_name='Телефон')),
                ('telegram_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Telegram Id')),
                ('vk_profile', models.URLField(blank=True, null=True, verbose_name='Профиль ВК')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Заметки о клиенте')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время курса')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Продолжительность курса')),
                ('name', models.CharField(max_length=100, verbose_name='Название курса')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость курса')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание лектора')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название программы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание курса')),
            ],
            options={
                'verbose_name': 'программа',
                'verbose_name_plural': 'программы',
            },
        ),
        migrations.CreateModel(
            name='CourseClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Отзыв клиента')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='courses.client', verbose_name='клиент')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='courses.course', verbose_name='курс')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='clients',
            field=models.ManyToManyField(related_name='courses', through='courses.CourseClient', to='courses.client', verbose_name='Клиенты'),
        ),
        migrations.AddField(
            model_name='course',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.lecturer', verbose_name='лектор'),
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.program', verbose_name='программа'),
        ),
    ]
