# Generated by Django 4.1.7 on 2023-02-26 05:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'get_latest_by': 'scheduled_at', 'ordering': ['-scheduled_at'], 'verbose_name': 'курс', 'verbose_name_plural': 'курсы'},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='date',
            new_name='scheduled_at',
        ),
        migrations.AddField(
            model_name='client',
            name='registered_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время регистрации'),
        ),
    ]
