# Generated by Django 4.1.7 on 2023-03-18 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название офиса')),
                ('image', models.ImageField(upload_to='office', verbose_name='Фото офиса')),
                ('long', models.DecimalField(decimal_places=14, max_digits=17, validators=[django.core.validators.MinValueValidator(limit_value=-180), django.core.validators.MaxValueValidator(limit_value=180)])),
                ('lat', models.DecimalField(decimal_places=14, max_digits=16, validators=[django.core.validators.MinValueValidator(limit_value=-90), django.core.validators.MaxValueValidator(limit_value=90)])),
            ],
        ),
    ]
