# Generated by Django 4.1.7 on 2023-02-26 09:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_client_options_alter_lecturer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание лектора'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание курса'),
        ),
    ]
