# Generated by Django 4.1.7 on 2023-03-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_office_options_office_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telegram_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Telegram Id'),
        ),
    ]
