# Generated by Django 4.1.7 on 2023-02-26 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lecturer_description_alter_program_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseclient',
            options={'verbose_name': 'Курс - клиент', 'verbose_name_plural': 'Курсы по клиентам'},
        ),
    ]
