# Generated by Django 4.1.7 on 2023-02-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_courseclient_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='program/<django.db.models.fields.CharField>/', verbose_name='Иллюстрация программы'),
        ),
    ]
