# Generated by Django 4.1.7 on 2023-02-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_program_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='program/', verbose_name='Иллюстрация программы'),
        ),
    ]
