# Generated by Django 4.1.7 on 2023-04-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_program_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
