# Generated by Django 4.1.7 on 2023-04-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_lecturer_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduatePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='graduate_photos')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Выпуск')),
            ],
        ),
    ]
