# Generated by Django 4.1.7 on 2023-02-27 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_courseimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseimage',
            options={'ordering': ['position'], 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото к курсу'},
        ),
    ]
