# Generated by Django 4.1.7 on 2023-04-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_rename_photo_graduatephoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(default='default', null=True),
        ),
    ]
