# Generated by Django 4.1.7 on 2023-02-27 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_courseimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseimage',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='courses.course', verbose_name='Курс'),
        ),
    ]
