# Generated by Django 4.1.7 on 2023-03-04 16:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_courseimage_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание курса'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание программы'),
        ),
    ]
