# Generated by Django 4.1.7 on 2023-04-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_program_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseimage',
            name='image_preview',
            field=models.ImageField(blank=True, null=True, upload_to='courses'),
        ),
    ]
