# Generated by Django 4.1.7 on 2023-03-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bot_state',
            field=models.CharField(default='START', help_text='Стейт-машина бота', max_length=50, verbose_name='Текущее состояние бота'),
        ),
    ]
