# Generated by Django 4.1.7 on 2023-05-17 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_program_options_program_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_interval', models.PositiveSmallIntegerField(default=18, verbose_name='yапомнить за')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='reminder_intervals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.timer', verbose_name='напомнить за, ч.'),
        ),
    ]
