# Generated by Django 4.1.7 on 2023-05-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_timer_course_reminder_intervals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='reminder_intervals',
        ),
        migrations.AddField(
            model_name='course',
            name='reminder_intervals',
            field=models.ManyToManyField(related_name='courses', to='courses.timer', verbose_name='напомнить за, ч.'),
        ),
    ]
