# Generated by Django 4.1.7 on 2023-03-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_courseimage_image_vk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='vk_album_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Идентификатор альбома ВК для курса'),
        ),
    ]
