# Generated by Django 4.1.7 on 2023-05-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_timer_options_alter_course_reminder_intervals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='reminder_intervals',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.timer', verbose_name='напомнить за'),
        ),
    ]
