# Generated by Django 4.1.7 on 2023-03-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_course_vk_album_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Сокращенное описание'),
        ),
    ]
