# Generated by Django 4.1.7 on 2023-05-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_course_reminder_intervals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255, verbose_name='Имя задачи')),
                ('coro', models.CharField(max_length=100, verbose_name='Имя корутины')),
                ('timers', models.JSONField(blank=True, null=True, verbose_name='Список таймеров')),
                ('args', models.JSONField(blank=True, null=True, verbose_name='Позиционные аргументы')),
                ('kwargs', models.JSONField(blank=True, null=True, verbose_name='Именованные аргументы')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
                'ordering': ['task_name'],
            },
        ),
    ]
