# Generated by Django 4.1.7 on 2023-03-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_course_short_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'get_latest_by': 'scheduled_at', 'ordering': ['scheduled_at'], 'verbose_name': 'курс', 'verbose_name_plural': 'курсы'},
        ),
    ]
