# Generated by Django 4.1.7 on 2023-05-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
    ]
