# Generated by Django 4.1.7 on 2023-03-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_program_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseimage',
            name='upload_vk',
            field=models.BooleanField(default=True, verbose_name='Загрузить в ВК'),
        ),
    ]
