# Generated by Django 4.1.7 on 2023-03-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_courseimage_upload_vk'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='published_in_bot',
            field=models.BooleanField(default=True, verbose_name='В боте'),
        ),
    ]
