# Generated by Django 4.1.7 on 2023-05-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_task_call_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_timers',
            field=models.JSONField(blank=True, null=True, verbose_name='Список выполненных таймеров'),
        ),
    ]
