# Generated by Django 4.1.7 on 2023-05-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_task_completed_timers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_timers',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Список выполненных таймеров'),
        ),
        migrations.AlterField(
            model_name='task',
            name='timers',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Список таймеров'),
        ),
    ]
