# Generated by Django 4.1.7 on 2023-05-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_alter_task_completed_timers_alter_task_timers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='args',
            field=models.JSONField(blank=True, default='[]', null=True, verbose_name='Позиционные аргументы'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_timers',
            field=models.JSONField(blank=True, default='[]', null=True, verbose_name='Список выполненных таймеров'),
        ),
        migrations.AlterField(
            model_name='task',
            name='kwargs',
            field=models.JSONField(blank=True, default='{}', null=True, verbose_name='Именованные аргументы'),
        ),
        migrations.AlterField(
            model_name='task',
            name='timers',
            field=models.JSONField(blank=True, default='[]', null=True, verbose_name='Список таймеров'),
        ),
    ]
