# Generated by Django 4.1.7 on 2023-06-01 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_client_completed_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок')),
                ('message', models.TextField(null=True, verbose_name='Сообщение')),
                ('client_status', models.CharField(blank=True, choices=[('all', 'Для всех'), ('no_courses', 'Не проходили курсов'), ('past_courses', 'Проходили курсы'), ('future_courses', 'Записаны на курсы'), ('past_courses_no_future', 'Проходили но не записаны на курсы'), ('fresh_register', 'Недавно зарегистрировались')], db_index=True, default='all', max_length=50, null=True, verbose_name='Сообщения для клиентов')),
                ('scheduled_at', models.DateTimeField(verbose_name='Дата и время отправки')),
                ('repeat_interval', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Повторять через, мин.')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='courses.client', verbose_name='Сообщение для клиента')),
            ],
        ),
    ]
