# Generated by Django 4.1.7 on 2023-06-01 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_scheduledmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledmessage',
            options={'ordering': ['-scheduled_at'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Отправка сообщений'},
        ),
    ]
